apiVersion: v1
kind: Service
metadata:
  name: lobwife
  namespace: lobmob
  labels:
    app.kubernetes.io/name: lobwife
    app.kubernetes.io/part-of: lobmob
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lobwife
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: api
